 server:
  port: 1212
  
 spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
  datasource:  
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    
  mvc:
    view:
      prefix: /views/
      suffix: .jsp  
